name: Build App

on:
  # Trigger mega-linter at Pull Requests to main
  pull_request:
    branches: [main]

jobs:
  build:
    name: BuildApp
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore SpiderScreensaver.sln

      - name: Build Solution
        run: |
          msbuild.exe SpiderScreensaver.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Artifact prep 
        run: | 
          cp MyScreensaver_wpf/bin/MyScreensaver_wpf.exe MyScreensaver_wpf/bin/MyScreensaver_wpf.src
          cp MyScreensaver_wpf/bin/MyScreensaver_wpf.src bin
      - name: Publish bin artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: |
            bin
      - name: Create Draft Release
      id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: <tofill>
          release_name: <tofill>
          draft: true
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: bin
          asset_name: my-artifact.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}